joints:
# Right Arm
- name: /right/j1
  index: 0
- name: /right/j2
  index: 1
- name: /right/j3
  index: 2
- name: /right/j4
  index: 3
- name: /right/j5
  index: 4
- name: /right/j6
  index: 5
- name: /right/j7
  index: 6
# Right Hand
- name: /right/j01
  index: 7
- name: /right/j11
  index: 8
- name: /right/j21
  index: 9
- name: /right/j00
  index: 10
# Left Arm
- name: /left/j1
  index: 11
- name: /left/j2
  index: 12
- name: /left/j3
  index: 13
- name: /left/j4
  index: 14
- name: /left/j5
  index: 15
- name: /left/j6
  index: 16
- name: /left/j7
  index: 17
# Left Hand
- name: /left/j01
  index: 18
- name: /left/j11
  index: 19
- name: /left/j21
  index: 20
- name: /left/j00
  index: 21
# Head
- name: /head/wam1
  index: 22
- name: /head/wam2
  index: 23
# Passive/Mimic Joints
- name: /left/j02
  index: 24
- name: /left/j12
  index: 25
- name: /left/j22
  index: 26
- name: /left/j10
  index: 27
- name: /right/j02
  index: 28
- name: /right/j12
  index: 29
- name: /right/j22
  index: 30
- name: /right/j10
  index: 31
adjacent:
- [ /left/wam1,       /left/wam3      ]
- [ /right/wam1,      /right/wam3     ]
- [ /left/wam1,       /right/wam1     ]
# Left Arm
- [ /left/wam1,       /herb_base      ]
- [ /left/wam4,       /left/wam6      ]
- [ /left/wam4,       /left/wam7      ]
# Right Arm
- [ /right/wam1,      /herb_base      ]
- [ /right/wam4,      /right/wam6     ]
- [ /right/wam4,      /right/wam7     ]
## Head
- [ /head/wam1, /head/wam2 ]
- [ /head/wam1, /herb_base ]
- [ /head/wam2, /herb_base ]
## Autogenerated pairwise combinations between finger links
## (only within the same hand)
- [ /left/finger0_2 , /left/hand_base ]
- [ /left/finger1_2 , /left/hand_base ]
- [ /left/finger1_0 , /left/finger1_1 ]
- [ /left/finger0_0 , /left/finger2_1 ]
- [ /left/finger1_1 , /left/finger2_1 ]
- [ /left/finger0_1 , /left/hand_base ]
- [ /left/finger0_0 , /left/finger1_1 ]
- [ /left/finger0_1 , /left/finger0_2 ]
- [ /left/finger0_2 , /left/finger2_1 ]
- [ /left/finger0_1 , /left/finger1_0 ]
- [ /left/finger1_2 , /left/finger2_2 ]
- [ /left/finger1_0 , /left/finger1_2 ]
- [ /left/finger0_0 , /left/hand_base ]
- [ /left/finger2_2 , /left/hand_base ]
- [ /left/finger0_0 , /left/finger2_2 ]
- [ /left/finger0_0 , /left/finger1_0 ]
- [ /left/finger1_1 , /left/finger1_2 ]
- [ /left/finger0_2 , /left/finger1_2 ]
- [ /left/finger0_2 , /left/finger2_2 ]
- [ /left/finger0_1 , /left/finger1_1 ]
- [ /left/finger1_1 , /left/finger2_2 ]
- [ /left/finger0_1 , /left/finger2_2 ]
- [ /left/finger1_2 , /left/finger2_1 ]
- [ /left/finger1_0 , /left/finger2_2 ]
- [ /left/finger2_1 , /left/hand_base ]
- [ /left/finger0_0 , /left/finger0_1 ]
- [ /left/finger1_0 , /left/hand_base ]
- [ /left/finger0_2 , /left/finger1_1 ]
- [ /left/finger2_1 , /left/finger2_2 ]
- [ /left/finger0_1 , /left/finger1_2 ]
- [ /left/finger1_1 , /left/hand_base ]
- [ /left/finger0_1 , /left/finger2_1 ]
- [ /left/finger0_0 , /left/finger0_2 ]
- [ /left/finger0_0 , /left/finger1_2 ]
- [ /left/finger1_0 , /left/finger2_1 ]
- [ /left/finger0_2 , /left/finger1_0 ]
- [ /right/finger0_0 , /right/finger0_2 ]
- [ /right/finger0_1 , /right/finger1_1 ]
- [ /right/finger1_0 , /right/finger2_1 ]
- [ /right/finger1_1 , /right/hand_base ]
- [ /right/finger1_2 , /right/finger2_2 ]
- [ /right/finger0_2 , /right/finger1_1 ]
- [ /right/finger0_2 , /right/finger2_1 ]
- [ /right/finger1_0 , /right/finger1_1 ]
- [ /right/finger0_0 , /right/finger2_2 ]
- [ /right/finger0_0 , /right/hand_base ]
- [ /right/finger0_2 , /right/finger1_2 ]
- [ /right/finger0_1 , /right/finger2_2 ]
- [ /right/finger1_2 , /right/finger2_1 ]
- [ /right/finger0_2 , /right/finger1_0 ]
- [ /right/finger0_1 , /right/finger1_2 ]
- [ /right/finger0_1 , /right/finger0_2 ]
- [ /right/finger0_2 , /right/finger2_2 ]
- [ /right/finger0_0 , /right/finger1_2 ]
- [ /right/finger2_2 , /right/hand_base ]
- [ /right/finger1_0 , /right/finger1_2 ]
- [ /right/finger1_1 , /right/finger1_2 ]
- [ /right/finger0_1 , /right/finger2_1 ]
- [ /right/finger1_1 , /right/finger2_2 ]
- [ /right/finger1_2 , /right/hand_base ]
- [ /right/finger1_0 , /right/hand_base ]
- [ /right/finger1_0 , /right/finger2_2 ]
- [ /right/finger0_0 , /right/finger1_1 ]
- [ /right/finger0_0 , /right/finger0_1 ]
- [ /right/finger0_1 , /right/finger1_0 ]
- [ /right/finger0_2 , /right/hand_base ]
- [ /right/finger2_1 , /right/hand_base ]
- [ /right/finger2_1 , /right/finger2_2 ]
- [ /right/finger0_1 , /right/hand_base ]
- [ /right/finger0_0 , /right/finger2_1 ]
- [ /right/finger0_0 , /right/finger1_0 ]
- [ /right/finger1_1 , /right/finger2_1 ]
